// Parallel guide copy: English | Japanese | Spanish. No user data or HTML.
export const guide = {
  intro: "Start with one question. You can leave unknowns open and return later.|まずは1問だけで大丈夫です。分からないことは未決定のまま残し、後で続けられます。|Empieza con una pregunta. Puedes dejar dudas abiertas y volver después.",
  purpose: "This tool records what to build or introduce, whose view it is, and what has actually been agreed. It does not generate a game or run an AI agent.|このツールは、何を作る・導入するか、誰の考えか、どこまで合意したかを整理します。ゲームの生成やAIエージェントの実行をするものではありません。|Esta herramienta registra qué crear o implantar, de quién es cada opinión y qué se ha acordado. No genera juegos ni ejecuta agentes de IA.",
  conceptsTitle: "Three things to keep separate|最初に知っておきたい3つの違い|Tres cosas que conviene distinguir",
  concepts: [
    ["Contribution = a reported answer|Contribution＝誰かの回答|Contribution = respuesta de una fuente", "For example: a support worker says that searching the FAQ takes time. Saving it records their view; it does not make it a project decision.|例：問い合わせ担当者が「FAQを探すのに時間がかかる」と答えた。その人の認識を記録した段階で、プロジェクトの決定ではありません。|Por ejemplo: una persona de soporte dice que buscar en las FAQ lleva tiempo. Guardarlo registra su perspectiva, no una decisión del proyecto."],
    ["Resolution = how the project treats that answer|Resolution＝プロジェクトとしての採用判断|Resolution = cómo lo trata el proyecto", "Choose whether to adopt an answer provisionally, confirm it, request a proposal, or leave it undecided. An answer and a decision are separate records.|その回答を暫定的に採用するか、確定するか、提案を求めるか、未決定にするかを選びます。回答を入力しただけでは採用されません。|Elige adoptar una respuesta provisionalmente, confirmarla, solicitar propuestas o dejarla pendiente. Introducir una respuesta no la adopta automáticamente."],
    ["Base = an explicitly saved reference revision|Base＝明示的に確定した基準の版|Base = versión de referencia confirmada", "In Review, confirm the current collection of premises as Base r1. Undecided items may remain undecided. Later edits require a new Base confirmation to appear in exports.|レビューで、その時点の前提をまとめてBase r1として確定します。未決定の項目があっても構いません。その後の編集を出力に含めるには、改めて次のBaseを確定します。|En Revisión, confirma el conjunto actual como Base r1. Puede contener asuntos pendientes. Los cambios posteriores requieren confirmar otra Base para aparecer en la exportación."]
  ],
  stepsTitle: "Try one complete input, from start to export|まず1問を入力して、出力まで試す|Prueba una pregunta desde el inicio hasta la exportación",
  steps: [
    ["Choose the subject on the home page|ホームで対象を選ぶ|Elige el tema en el inicio", "Websites & Small Web Apps has 42 questions, Game Development has 40, and AI Agent Adoption Planning has 48. Choose for the work you want to align, not the tool you plan to use.|Webサイト・小規模Webアプリは42問、ゲーム制作は40問、AIエージェント導入計画は48問です。使う技術ではなく、整理したい仕事に合うものを選びます。|Webs y pequeñas aplicaciones tiene 42 preguntas; juegos, 40; adopción de agentes de IA, 48. Elige según el trabajo que quieras alinear."],
    ["Identify the project and the people|プロジェクトと回答する人を設定する|Identifica el proyecto y las personas", "Enter a project name and the recorder's label and role. The recorder is the person entering the answer. Select decision authority only if they really can approve the premise. For an interview, enable the separate perspective option and identify the person whose answer is being recorded.|プロジェクト名、記録者の表示名と役割を入力します。記録者は入力する人です。その人が実際に要件を承認できる場合だけ、決定権のチェックを入れます。聞き取りなら「別の人またはグループから得た回答を記録する」を選び、回答元を設定します。|Introduce nombre del proyecto, nombre y rol de quien registra. Marca autoridad de decisión solo si puede aprobar realmente las premisas. En entrevistas, activa la perspectiva de otra persona e identifica la fuente."],
    ["Answer one question and add the reason|1問に答え、理由を補足する|Responde una pregunta y añade el motivo", "Select an option or enter text. Add background, evidence or limits in Context or rationale. Check the perspective, recorder and capture method. These fields describe the source, not the strength of the answer. Other options may require a note.|選択肢を選ぶか、文章を入力します。「コンテキストまたは理由」には背景、根拠、限界を書きます。回答元・記録者・取得方法も確認してください。これは答えの強さではなく出所の情報です。「その他」などでは補足が必須です。|Selecciona una opción o escribe. Añade contexto, evidencia o límites en Contexto o motivo. Comprueba perspectiva, registrador y método: describen la fuente, no la fuerza de la respuesta. Otra opción puede exigir una nota."],
    ["Decide how to use the answer|入力した回答をどう扱うか選ぶ|Decide cómo usar la respuesta", "For a first trial, choose Provisional under Resolution status. Check that Source contribution shows the answer you intend to use. This lets you try the flow without claiming final agreement. If you do not know yet, leave Not decided or use Leave unresolved, then move on.|最初の練習では、質問の下にある「Resolutionの状態」で「暫定」を選びます。「前提値の取得元」が採用したい回答になっているか確認してください。最終合意とせず、仮の前提として進められます。まだ決められない場合は「未決定」や「未解決のままにする」で先に進めます。|Para empezar, elige Provisional en Estado de Resolution y comprueba la contribución de origen. Así pruebas el flujo sin afirmar un acuerdo final. Si aún no sabes, deja Sin decidir o usa Dejar sin resolver y continúa."],
    ["Review and confirm a Base|レビューしてBaseを確定する|Revisa y confirma una Base", "Open Review, inspect unresolved items, warnings and sources, then choose Confirm Base revision and confirm the dialog. This freezes a reference version; it does not declare every answer correct or every issue resolved.|「レビュー」を開き、未決定事項、警告、回答の出所を確認します。「Baseリビジョンを確定」を押し、確認ダイアログで確定します。基準の版を残す操作であり、全項目が正しい・解決したという宣言ではありません。|Abre Revisión, comprueba pendientes, avisos y fuentes, y pulsa Confirmar revisión Base. Confirma el diálogo. Fija una referencia; no declara correctas todas las respuestas ni resueltos todos los asuntos."],
    ["Export a backup or an AI handoff|バックアップやAIへの引き継ぎを出力する|Exporta una copia o un contexto para IA", "Open Export. Download Base JSON to save the confirmed reference. Download AI Context to give an AI the premises, sources and unknowns. The latest draft is not exported until you confirm a new Base.|「エクスポート」を開きます。確定した基準を保存するなら「Baseをダウンロード」、AIに前提・出所・不明点を渡すなら「AI Contextをダウンロード」を選びます。編集中の最新版は、新しいBaseを確定するまで出力されません。|Abre Exportar. Descarga Base JSON para guardar la referencia o AI Context para entregar premisas, fuentes y dudas a una IA. El borrador más reciente no se exporta hasta confirmar una nueva Base."]
  ],
  examplesTitle: "Examples for each template|テンプレート別の入力例|Ejemplos por plantilla",
  examplesIntro: "These are fictional examples to help you write. Opening them does not fill in or change your project.|書き方を理解するための架空例です。開いてもプロジェクトへの自動入力や変更は行いません。|Son ejemplos ficticios para orientarte. Abrirlos no rellena ni modifica tu proyecto.",
  examples: [
    ["Website: an inquiry page|Web制作：問い合わせページ|Web: página de consultas", [
      ["Question|質問|Pregunta", "What is the primary outcome this release should enable?|このリリースで実現すべき主な成果は何ですか？|¿Cuál es el resultado principal que debe permitir esta entrega?"],
      ["Answer|回答|Respuesta", "Generate inquiries or leads|問い合わせや見込み客を獲得する|Generar consultas o contactos"],
      ["Context|補足|Contexto", "First-time visitors should understand the service and send an inquiry. Online payment is outside this release. Check the flow with three people unfamiliar with the service.|初めて訪れた人がサービスを理解し、問い合わせできるようにしたい。今回、オンライン決済は含めない。サービスを知らない3人に操作を試してもらう。|Los visitantes nuevos deben entender el servicio y enviar una consulta. El pago en línea queda fuera. Probar el flujo con tres personas que no conozcan el servicio."],
      ["Source and Resolution|出所と採用判断|Fuente y Resolution", "Requester reports the goal; recorder enters it. Use Provisional while the decision owner reviews it.|依頼者の希望を記録者が入力。決定権者に確認するまでは「暫定」として扱う。|El solicitante comunica el objetivo y otra persona lo registra. Mantenerlo Provisional hasta la revisión del decisor."]
    ]],
    ["Game: a small exploration prototype|ゲーム制作：小さな探索ゲームの試作|Juego: prototipo de exploración", [
      ["Question|質問|Pregunta", "What should this release achieve?|今回の制作で何を達成しますか？|¿Qué debe lograr esta entrega?"],
      ["Answer|回答|Respuesta", "Test the core play with a prototype.|試作で遊びの核を検証。|Probar el juego básico con un prototipo."],
      ["Context|補足|Contexto", "Build three rooms and two tools to test the fun of discovering a route. Aim for ten minutes of play. Multiplayer and final-quality art are out of scope.|部屋3つ・道具2つで、道を発見する楽しさを検証したい。10分程度で遊べる範囲にし、対戦と完成品質の美術は対象外。|Crear tres salas y dos herramientas para probar el descubrimiento de rutas. Unos diez minutos de juego; sin multijugador ni arte final."],
      ["Source and Resolution|出所と採用判断|Fuente y Resolution", "Record the creator's plan as Provisional. Add playtest feedback as another contribution rather than overwriting the original plan.|制作者の案を「暫定」として採用。プレイテストの声は元の案を上書きせず、別の観点として追加する。|Registrar el plan del creador como Provisional. Añadir comentarios de pruebas como otra contribución, sin sobrescribir el plan."]
    ]],
    ["AI agent: draft a support reply|AI導入：問い合わせの返信案作成|Agente de IA: borrador de respuesta", [
      ["Question|質問|Pregunta", "What work should change, for whom?|誰の、どの仕事を変えたいですか？|¿Qué trabajo debe cambiar y para quién?"],
      ["Answer|回答|Respuesta", "Help support staff draft replies using approved FAQ sources. Staff send the replies themselves.|問い合わせ担当者が、承認済みFAQを根拠に返信案を作る。送信は担当者が行う。|Ayudar al personal a redactar respuestas con FAQ aprobadas. El personal realiza el envío."],
      ["Context|補足|Contexto", "We expect to reduce working time, but the current total is not measured. Compare search, drafting, review and correction time. Do not assume savings before evaluation.|作業時間の削減を期待しているが、現在の総工数は未計測。検索・作成・確認・修正を含めて比較する。検証前に削減効果を確定扱いしない。|Esperamos ahorrar tiempo, pero el total actual no está medido. Comparar búsqueda, redacción, revisión y corrección; no dar el ahorro por demostrado."],
      ["Source and Resolution|出所と採用判断|Fuente y Resolution", "Keep management expectations and frontline observations as separate contributions. Adopt the trial scope provisionally and leave unmeasured effects open.|導入側の期待と現場の観察を分けて記録。試行する範囲は「暫定」とし、未計測の効果は未確認のまま残す。|Separar expectativas de dirección y observaciones del personal. Adoptar provisionalmente el alcance del piloto y mantener los efectos sin medir como no comprobados."]
    ]]
  ],
  statesTitle: "Which Resolution status should I choose?|Resolutionの状態で迷ったら|¿Qué estado de Resolution elijo?",
  states: [
    ["Not decided|未決定|Sin decidir", "No adopted premise yet. Do not fill the gap by guessing.|まだ採用する前提を決めない。推測で埋める必要はありません。|Aún no hay una premisa adoptada. No hace falta rellenarla con suposiciones."],
    ["Provisional|暫定|Provisional", "Use the selected answer for now, with room to revise.|選んだ回答を当面の前提にする。後で見直せます。|Usar por ahora la respuesta elegida, abierta a revisión."],
    ["Confirmed|確定|Confirmada", "An authorized decider accepts this premise. This is not proof that a predicted benefit will occur.|決定権のある人が採用を認めた前提。将来の効果が実証された、という意味ではありません。|Una persona autorizada acepta la premisa. No demuestra que un beneficio futuro vaya a ocurrir."],
    ["Ask for a proposal|提案を求める|Solicitar una propuesta", "Request options or advice without choosing an answer yet.|選択肢や案を求める。まだ答えを選んだことにはしません。|Pedir opciones o consejo sin elegir todavía una respuesta."],
    ["Delegate within bounds|範囲を定めて委任|Delegar dentro de límites", "An authorized decider delegates a decision within recorded limits. Explain those limits in the note.|権限のある人が、記録した範囲内の判断を任せる。補足に限界や条件を書きます。|Una persona autorizada delega dentro de límites registrados. Explica esos límites en la nota."],
    ["Does not apply|該当なし|No corresponde", "An authorized decider determines that the question is outside this project. This is different from not knowing.|権限のある人が、このプロジェクトには当てはまらないと判断。「分からない」とは別です。|Una persona autorizada decide que la pregunta no se aplica. No equivale a no saber."]
  ],
  filesTitle: "Which file should I save?|どのファイルを保存すればよい？|¿Qué archivo debo guardar?",
  files: [
    ["Base JSON|Base JSON|Base JSON", "The last confirmed reference. Start with this for a portable backup.|最後に確定した基準の版。まずはこちらをバックアップとして保存します。|La última referencia confirmada. Empieza por esta copia portátil."],
    ["Override JSON|Override JSON|Override JSON", "An optional scoped change tied to a specific Base revision. You do not need it for your first project. Preserve the matching Base too.|特定のBaseに対する、範囲を限定した変更。最初は使わなくて構いません。対応するBaseも一緒に保管します。|Cambio opcional acotado a una revisión Base. No hace falta al empezar. Conserva también la Base correspondiente."],
    ["Unified JSON|Unified JSON|Unified JSON", "The result of applying active Overrides to Base. Keep Base and Override files separately if you need to preserve the individual changes.|Baseに有効なOverrideを反映した結果。個別の変更も保管したい場合はBaseとOverrideを別途保存します。|Resultado de aplicar Overrides activos a la Base. Guarda Base y Overrides por separado para conservar los cambios individuales."],
    ["AI Context Markdown|AI Context Markdown|AI Context Markdown", "A readable handoff for an AI, including sources and unknowns. Give it with the task you want performed. To reopen a project in this app, use JSON instead.|出所や不明点を含む、AI向けの読みやすい引き継ぎ文書。依頼したい作業と一緒にAIへ渡します。このアプリへの再読み込みにはJSONを使います。|Contexto legible para una IA con fuentes y dudas. Entrégalo junto a la tarea. Para reabrir el proyecto aquí, usa JSON."]
  ],
  faqTitle: "When you get stuck|困ったときは|Si te atascas",
  faq: [
    ["Do I have to answer everything?|全部答えないと進めませんか？|¿Tengo que responder todo?", "No. Use Next question, Leave unresolved or the category list. You can confirm a Base with undecided items; they remain visible in the handoff.|いいえ。「次の質問」「未解決のままにする」やカテゴリ一覧で移動できます。未決定事項を含むBaseも確定でき、引き継ぎ先にも不明点として残ります。|No. Usa Siguiente pregunta, Dejar sin resolver o las categorías. Puedes confirmar una Base con pendientes que seguirán visibles al compartirla."],
    ["Why does my answer still say Not decided?|回答したのに「未決定」のままです。|¿Por qué sigue Sin decidir tras responder?", "The answer was saved as a Contribution. To adopt it, choose a Resolution status and check the source contribution below the question.|回答はContributionとして保存されています。採用するには、質問の下でResolutionの状態と前提値の取得元を選びます。|La respuesta se guardó como Contribution. Para adoptarla, elige un estado de Resolution y comprueba la contribución de origen bajo la pregunta."],
    ["How do I confirm an individual premise?|項目を「確定」にするには？|¿Cómo confirmo una premisa individual?", "First choose Provisional, check the source contribution and select the appropriate Decider; then switch to Confirmed. If no authorized decider is available, keep it provisional or unresolved and obtain their input. Do not claim authority just to enable the control.|まず「暫定」を選び、前提値の取得元を確認して、適切な「決定者」を選んでから「確定」に切り替えます。権限のある人がいない場合は暫定・未決定にして確認を取りましょう。操作を有効にするためだけに決定権を付けないでください。|Elige primero Provisional, comprueba el origen y selecciona al Decisor adecuado; después cambia a Confirmada. Sin autoridad disponible, mantenla provisional o pendiente y consulta a la persona responsable."],
    ["Two people give different answers. Which do I keep?|人によって答えが違うときは？|¿Qué hago si dos personas responden distinto?", "Use Add another perspective and set the source for each answer. Keep both accounts; select the adopted answer separately in Resolution. An unresolved difference can remain a conflict.|「観点を追加」で回答元を設定し、それぞれの回答を残します。採用する答えはResolutionで別に選びます。決着していない違いは、競合として残して構いません。|Usa Añadir otra perspectiva y asigna la fuente de cada respuesta. Conserva ambas y selecciona la adoptada en Resolution. Una diferencia sin resolver puede quedar como conflicto."],
    ["Why are recent edits missing from the export?|編集した内容が出力に入りません。|¿Por qué no aparecen los cambios al exportar?", "Exports use the last confirmed Base. Open Review and confirm the next revision, such as r2. Draft autosave and Base confirmation are different actions.|出力には最後に確定したBaseを使います。「レビュー」で次の版（r2など）を確定してください。下書きの自動保存とBase確定は別です。|Las exportaciones usan la última Base confirmada. Confirma la siguiente revisión, como r2, en Revisión. Guardar el borrador y confirmar Base son acciones distintas."],
    ["Where is my work saved, and how do I resume?|保存先と、次回の再開方法は？|¿Dónde se guarda y cómo continúo?", "Drafts save in this browser when storage is available. Reopen from Recent projects on the same browser and site. There is no cloud sync: another device or clearing site data can lose access. Export JSON and use Import JSON to bring back the confirmed content; do not rely on JSON to preserve an unconfirmed draft.|保存可能な場合、下書きはこのブラウザに自動保存されます。同じブラウザ・同じサイトの「最近のプロジェクト」から再開します。クラウド同期はなく、別端末では表示されず、サイトデータを消すと失われます。JSONを保存し、「JSONをインポート」で確定済みの内容を戻せます。未確定の下書きはJSONに含まれない点に注意してください。|Los borradores se guardan en este navegador si hay almacenamiento disponible. Continúa desde Proyectos recientes en el mismo navegador y sitio. No hay sincronización: otro dispositivo no los verá y borrar datos puede eliminarlos. Exporta JSON e impórtalo para recuperar contenido confirmado, no borradores sin confirmar."]
  ]
};

export function guideText(value, locale) {
  const index = { en: 0, ja: 1, es: 2 }[locale] ?? 0;
  return value.split("|")[index];
}
